export {default as Home} from "./Home"
export {default as Projects} from "./Projects"
export {default as Edu} from "./Edu"
export {default as Links} from "./Links"
export {default as Resume} from "./Resume"
export {default as Skills} from "./Skills"